### ISSUE TITLE
Ӊ interpolation issue

### ISSUE THREAD

**Issue by thlinard** [googlefonts/OswaldFont#20]
https://fonts.google.com/specimen/Oswald?preview.text=%D3%89&preview.text_type=custom

See https://type.today/en/journal/neo

**Comment by kenmcd** [comment]
This one appears to have already been fixed in the `Oswald.glyphs` master.

**Comment by thlinard** [comment]
Oh, indeed! Live version is 4.100 (not fixed), the version here is 4.101 (fixed), with a PR waiting (version 4.102, fixed).

**Comment by thlinard** [comment]
Hi @aaronbell, do you know what happened? It seemed to me that the problem was corrected in 4.102, but I see that it reappeared by https://github.com/google/fonts/pull/3661. Did this come from when you switched the sources?

**Comment by aaronbell** [comment]
I'm a bit confused, honestly 😆. The source is correct, the variable font on this repro is correct, but the version that got merged into GF has the issue. No idea how that happened.

**Comment by thlinard** [comment]
Indeed!

The version in https://github.com/google/fonts/pull/3661 has 129,452 bytes (767 glyphs), and it's supposed to come from https://github.com/aaronbell/OswaldFont, where the file has 172,608 bytes (883 glyphs).

Maybe the easiest way is to do a new PR?

**Comment by fitojb** [comment]
Just for the record, the issue is still visible on the public Google Fonts catalog.

**Comment by aaronbell** [comment]
See https://github.com/google/fonts/pull/3893

The PR was blocked for the time being.

**Comment by alexeiva** [comment]
I confirm this is fixed in 4.103, which is currently live at catalogue

<img width="218" alt="Image" src="https://github.com/user-attachments/assets/ef334fce-6fbb-4d89-908f-14ab585b5ecf" />
<img width="238" alt="Image" src="https://github.com/user-attachments/assets/3761b05d-a4f7-4f09-8aa6-ae9c0cb3c027" />
